// This file was autogenerated by closure-primitives/depswriter.py.
// Please do not edit.
goog.addDependency('../closure-primitives/base.js', ['goog'], []);
goog.addDependency('../define/typedarray/hybrid.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../define/typedarray/use.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../src/CanvasTool/pngencoder.js', ['CanvasTool.PngEncoder'], ['Zlib.CRC32', 'Zlib.Deflate']);
goog.addDependency('../vendor/zlib.js/closure-primitives/base.js', ['goog'], []);
goog.addDependency('../vendor/zlib.js/define/typedarray/hybrid.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../vendor/zlib.js/define/typedarray/use.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../vendor/zlib.js/src/adler32.js', ['Zlib.Adler32'], ['USE_TYPEDARRAY', 'Zlib.Util']);
goog.addDependency('../vendor/zlib.js/src/bitstream.js', ['Zlib.BitStream'], ['USE_TYPEDARRAY']);
goog.addDependency('../vendor/zlib.js/src/crc32.js', ['Zlib.CRC32'], ['USE_TYPEDARRAY']);
goog.addDependency('../vendor/zlib.js/src/deflate.js', ['Zlib.Deflate'], ['USE_TYPEDARRAY', 'Zlib', 'Zlib.Adler32', 'Zlib.RawDeflate']);
goog.addDependency('../vendor/zlib.js/src/export_object.js', ['Zlib.exportObject'], ['Zlib']);
goog.addDependency('../vendor/zlib.js/src/gunzip.js', ['Zlib.Gunzip'], ['USE_TYPEDARRAY', 'Zlib.CRC32', 'Zlib.GunzipMember', 'Zlib.Gzip', 'Zlib.RawInflate']);
goog.addDependency('../vendor/zlib.js/src/gunzip_member.js', ['Zlib.GunzipMember'], []);
goog.addDependency('../vendor/zlib.js/src/gzip.js', ['Zlib.Gzip'], ['USE_TYPEDARRAY', 'Zlib.CRC32', 'Zlib.RawDeflate']);
goog.addDependency('../vendor/zlib.js/src/heap.js', ['Zlib.Heap'], ['USE_TYPEDARRAY']);
goog.addDependency('../vendor/zlib.js/src/huffman.js', ['Zlib.Huffman'], ['USE_TYPEDARRAY']);
goog.addDependency('../vendor/zlib.js/src/inflate.js', ['Zlib.Inflate'], ['USE_TYPEDARRAY', 'Zlib.Adler32', 'Zlib.RawInflate']);
goog.addDependency('../vendor/zlib.js/src/inflate_stream.js', ['Zlib.InflateStream'], ['USE_TYPEDARRAY', 'Zlib', 'Zlib.RawInflateStream']);
goog.addDependency('../vendor/zlib.js/src/rawdeflate.js', ['Zlib.RawDeflate'], ['USE_TYPEDARRAY', 'Zlib.BitStream', 'Zlib.Heap']);
goog.addDependency('../vendor/zlib.js/src/rawinflate.js', ['Zlib.RawInflate'], ['USE_TYPEDARRAY', 'Zlib.Huffman']);
goog.addDependency('../vendor/zlib.js/src/rawinflate_stream.js', ['Zlib.RawInflateStream'], ['USE_TYPEDARRAY', 'Zlib.Huffman']);
goog.addDependency('../vendor/zlib.js/src/unzip.js', ['Zlib.Unzip'], ['USE_TYPEDARRAY', 'Zlib.CRC32', 'Zlib.RawInflate', 'Zlib.Zip']);
goog.addDependency('../vendor/zlib.js/src/util.js', ['Zlib.Util'], []);
goog.addDependency('../vendor/zlib.js/src/zip.js', ['Zlib.Zip'], ['USE_TYPEDARRAY', 'Zlib.CRC32', 'Zlib.RawDeflate']);
goog.addDependency('../vendor/zlib.js/src/zlib.js', ['Zlib'], []);
